services:
  slim-chatui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slim-chatui
    volumes:
      - slim-chatui:/app/backend/data
    ports:
      - ${PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  slim-chatui: {}
