services:
  slim-chatui:
    image: ghcr.io/ahxxm/slim-chatui:main
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    container_name: slim-chatui
    volumes:
      - ./slim-chatui:/app/backend/data
    ports:
      - ${PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    depends_on:
      - litellm
    environment:
      - OPENAI_API_BASE_URLS=http://litellm:4000
      - OPENAI_API_KEYS=sk-0001
      - WEBUI_SECRET_KEY=some-32-byte-key-to-avoid-warnings
