"""drop model table

Revision ID: 47a1e91cb59c
Revises: 60695e81adf4
Create Date: 2026-07-25 20:49:03.336210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db

# revision identifiers, used by Alembic.
revision: str = "47a1e91cb59c"
down_revision: Union[str, None] = "60695e81adf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model",
        sa.Column("id", sa.TEXT(), nullable=False),
        sa.Column("user_id", sa.TEXT(), nullable=True),
        sa.Column("base_model_id", sa.TEXT(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=True),
        sa.Column("params", sa.TEXT(), nullable=True),
        sa.Column("meta", sa.TEXT(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("updated_at", sa.BIGINT(), nullable=True),
        sa.Column("created_at", sa.BIGINT(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###
