"""init

Revision ID: 51f81311abb3
Revises:
Create Date: 2026-03-02 19:49:57.846108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db

# revision identifiers, used by Alembic.
revision: str = "51f81311abb3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "chat",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("chat", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("share_id", sa.Text(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=True),
        sa.Column("meta", sa.JSON(), server_default="{}", nullable=True),
        sa.Column("folder_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("share_id"),
    )
    op.create_index("folder_id_idx", "chat", ["folder_id"], unique=False)
    op.create_index(
        "folder_id_user_id_idx", "chat", ["folder_id", "user_id"], unique=False
    )
    op.create_index(
        "updated_at_user_id_idx", "chat", ["updated_at", "user_id"], unique=False
    )
    op.create_index(
        "user_id_archived_idx", "chat", ["user_id", "archived"], unique=False
    )
    op.create_index("user_id_pinned_idx", "chat", ["user_id", "pinned"], unique=False)
    op.create_table(
        "config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "folder",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("items", sa.JSON(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("is_expanded", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "model",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("base_model_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("params", open_webui.internal.db.JSONField(), nullable=True),
        sa.Column("meta", open_webui.internal.db.JSONField(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", "user_id", name="pk_id_user_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("profile_image_url", sa.Text(), nullable=True),
        sa.Column("profile_banner_image_url", sa.Text(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("gender", sa.Text(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("info", sa.JSON(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "chat_file",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("chat_id", sa.Text(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=True),
        sa.Column("file_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "file_id", name="uq_chat_file_chat_file"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("chat_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Text(), nullable=True),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("model_id", sa.Text(), nullable=True),
        sa.Column("files", sa.JSON(), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column("embeds", sa.JSON(), nullable=True),
        sa.Column("done", sa.Boolean(), nullable=True),
        sa.Column("status_history", sa.JSON(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "chat_message_chat_parent_idx",
        "chat_message",
        ["chat_id", "parent_id"],
        unique=False,
    )
    op.create_index(
        "chat_message_model_created_idx",
        "chat_message",
        ["model_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "chat_message_user_created_idx",
        "chat_message",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_message_chat_id"), "chat_message", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_message_created_at"), "chat_message", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_chat_message_model_id"), "chat_message", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_message_user_id"), "chat_message", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_message_user_id"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_model_id"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_created_at"), table_name="chat_message")
    op.drop_index(op.f("ix_chat_message_chat_id"), table_name="chat_message")
    op.drop_index("chat_message_user_created_idx", table_name="chat_message")
    op.drop_index("chat_message_model_created_idx", table_name="chat_message")
    op.drop_index("chat_message_chat_parent_idx", table_name="chat_message")
    op.drop_table("chat_message")
    op.drop_table("chat_file")
    op.drop_table("user")
    op.drop_table("tag")
    op.drop_table("model")
    op.drop_table("folder")
    op.drop_table("file")
    op.drop_table("config")
    op.drop_index("user_id_pinned_idx", table_name="chat")
    op.drop_index("user_id_archived_idx", table_name="chat")
    op.drop_index("updated_at_user_id_idx", table_name="chat")
    op.drop_index("folder_id_user_id_idx", table_name="chat")
    op.drop_index("folder_id_idx", table_name="chat")
    op.drop_table("chat")
    op.drop_table("auth")
    # ### end Alembic commands ###
