"""drop tag table

Revision ID: 5db08303182b
Revises: 51f81311abb3
Create Date: 2026-03-05 22:54:31.546991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "5db08303182b"
down_revision: Union[str, None] = "51f81311abb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("user_id", sa.VARCHAR(), nullable=False),
        sa.Column("meta", sqlite.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", "user_id", name=op.f("pk_id_user_id")),
    )
    # ### end Alembic commands ###
