"""drop folder parent_id column

Revision ID: 5dd61be64f59
Revises: b6a03647fe06
Create Date: 2026-03-08 12:42:51.850796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db

# revision identifiers, used by Alembic.
revision: str = "5dd61be64f59"
down_revision: Union[str, None] = "b6a03647fe06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("folder", "parent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("folder", sa.Column("parent_id", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
