"""drop user PII columns

Revision ID: b6a03647fe06
Revises: 5db08303182b
Create Date: 2026-03-07 15:06:52.739571

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "b6a03647fe06"
down_revision: Union[str, None] = "5db08303182b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "info")
    op.drop_column("user", "profile_image_url")
    op.drop_column("user", "date_of_birth")
    op.drop_column("user", "bio")
    op.drop_column("user", "timezone")
    op.drop_column("user", "username")
    op.drop_column("user", "profile_banner_image_url")
    op.drop_column("user", "gender")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("gender", sa.TEXT(), nullable=True))
    op.add_column(
        "user", sa.Column("profile_banner_image_url", sa.TEXT(), nullable=True)
    )
    op.add_column("user", sa.Column("username", sa.VARCHAR(length=50), nullable=True))
    op.add_column("user", sa.Column("timezone", sa.VARCHAR(), nullable=True))
    op.add_column("user", sa.Column("bio", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("date_of_birth", sa.DATE(), nullable=True))
    op.add_column("user", sa.Column("profile_image_url", sa.TEXT(), nullable=True))
    op.add_column("user", sa.Column("info", sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
