"""drop embeds column from chat_message

Revision ID: cb611f7fb096
Revises: 5dd61be64f59
Create Date: 2026-03-11 20:32:13.760186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "cb611f7fb096"
down_revision: Union[str, None] = "5dd61be64f59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_message", "embeds")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_message", sa.Column("embeds", sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
